# Generated by Django 2.1.9 on 2020-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repositoryNew',
            fields=[
                ('idrepository', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(blank=True, choices=[('externo', 'Externos'), ('local', 'Local')], max_length=4000)),
                ('nameRepository', models.CharField(blank=True, max_length=4000)),
                ('resource', models.FileField(upload_to='portal/data/')),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'repositoryNew',
            },
        ),
    ]
