# Generated by Django 2.1.9 on 2020-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorynew',
            name='origin',
            field=models.CharField(blank=True, choices=[('external', 'External'), ('local', 'Local')], max_length=4000),
        ),
    ]
